language: dart
dart:
  - dev
cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.pub-cache/hosted
    - node_modules
before_install:
  - test "$ANALYZER" == stable || ./tool/override_analyzer_dependency.sh
  - pub global activate dart_coveralls
  - export CHROME_CANARY_BIN=`./tool/get_chrome_canary.sh`
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - nvm install 5.5.0
  - npm install
script:
  - ./tool/presubmit.sh && ./tool/coverage.sh
env:
  - ANALYZER=stable
  - ANALYZER=master
