'use strict';
require("./_debugger");
require("./html_common");
require("./html");
require("./_metadata");
require("./js");
require("./_js_mirrors");
require("./mirrors");
require("./convert");
require("./_js_primitives");
require("./_isolate_helper");
require("./_native_typed_data");
require("./typed_data");
require("./isolate");
require("./_js_helper");
require("./_js_embedded_names");
require("./_foreign_helper");
require("./async");
require("./_interceptors");
require("./math");
require("./_internal");
require("./collection");
require("./core");
let dart = require("./_runtime");
let math = require("./math");
let core = require("./core");
let dartx = dart.dartx;
dart.export(exports, math, ['Rectangle', 'Point'], []);
const RequestAnimationFrameCallback = dart.typedef('RequestAnimationFrameCallback', () => dart.functionType(dart.void, [core.num]));
const EventListener = dart.typedef('EventListener', () => dart.functionType(dart.dynamic, [Event]));
const _F1 = dart.typedef('_F1', () => dart.functionType(dart.dynamic, [dart.dynamic]));
const __CastType0 = dart.typedef('__CastType0', () => dart.functionType(core.bool, [Element]));
const __CastType2 = dart.typedef('__CastType2', () => dart.functionType(dart.dynamic, [dart.dynamic]));
// Exports:
exports.RequestAnimationFrameCallback = RequestAnimationFrameCallback;
exports.EventListener = EventListener;
