'use strict';
require("dart/_debugger");
require("dart/html_common");
require("dart/html");
require("dart/_metadata");
require("dart/js");
require("dart/_js_mirrors");
require("dart/mirrors");
require("dart/convert");
require("dart/_js_primitives");
require("dart/_isolate_helper");
require("dart/_native_typed_data");
require("dart/typed_data");
require("dart/isolate");
require("dart/_js_helper");
require("dart/_js_embedded_names");
require("dart/_foreign_helper");
require("dart/async");
require("dart/_interceptors");
require("dart/math");
require("dart/_internal");
require("dart/collection");
require("dart/core");
let dart = require("dart/_runtime");
let math = require("dart/math");
let core = require("dart/core");
let dartx = dart.dartx;
dart.export(exports, math, ['Rectangle', 'Point'], []);
const RequestAnimationFrameCallback = dart.typedef('RequestAnimationFrameCallback', () => dart.functionType(dart.void, [core.num]));
const EventListener = dart.typedef('EventListener', () => dart.functionType(dart.dynamic, [Event]));
const _F1 = dart.typedef('_F1', () => dart.functionType(dart.dynamic, [dart.dynamic]));
const __CastType0 = dart.typedef('__CastType0', () => dart.functionType(core.bool, [Element]));
const __CastType2 = dart.typedef('__CastType2', () => dart.functionType(dart.dynamic, [dart.dynamic]));
// Exports:
exports.RequestAnimationFrameCallback = RequestAnimationFrameCallback;
exports.EventListener = EventListener;
